config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get "homes/about" => 'homes#show'
  resources :books
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  attachment :profile_image

         validates :name, length: { minimum: 2 }
         validates :name, length: { maximum: 20 }
         validates :introduction, length: { maximum: 50 }
         validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
      before_action :authenticate_user!,except: [:show, :top]

  def after_sign_in_path_for(resource)
     user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!


  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @bookuser = @book.user
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
    flash[:notice] = "You have created a new book!"
    redirect_to book_path(@book_new)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
      
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated successfully!"
    redirect_to book_path(@book)
    else
      render:edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
  params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!


  def show
    @user = User.find(params[:id])
    @book = Book.new
    @bookuser = @user.books
  end

  def index
    @user = User.find(current_user.id)
    @book = User.new
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(users_params)
    redirect_to users_path
  end

  private
  def users_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_template.html.erb
<%= form_with model: book, local: true do |f| %>
  <h4>タイトル</h4>
    <%= f.text_field :title %>
  <h4>本の感想</h4>
    <%= f.text_area :body %>
  <%= f.submit 'Create book' %>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0  mx-auto">
      <h2 class="mt-3">Bookの編集</h2>

        <%# ここからエラーメッセージ %>
        <% if @book.errors.any? %>
          <div id="error_explanation">
            <div class="error"><%= pluralize(@book.errors.count, "error") %> prohibited this product from being saved:</div>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%# ここまでエラーメッセージ <%>


        <%= form_with model:@book, local: true do |f| %>
          <div class="form-group mt-3">
            <%= f.label :タイトル %>
            <%= f.text_field :title, class: "form-control" %>
          </div>

          <div class="form-group mt-3" %>
            <%= f.label :本の感想 %>
            <%= f.text_area :body, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.submit "本の更新", class:"btn btn-success" %>
          </div>
        <% end %>
        <%= link_to "Show", books_path %> | <%= link_to " back", book_path(@book) %>
      </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user_template', user:@user %>
      <%= render 'books/book_template', book:@book %>
    </div>



  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table">
        <thead>
          <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th></th>
            </tr>
          </thead>
        <tbody>
        <% @books.each do |book| %>
            <tr>
              <td><%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
              <td><%= book.title %></td>
              <td><%= link_to "Show", book_path(book) %></td>
            </tr>
        <% end %>
      </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user_template', user:@bookuser %>
      <%= render 'books/book_template', book:@book_new %>
    </div>
  <div class="col-md-8 offset-md-1">
    <h2>Book Detail</h2>
    <table class="table">
      <thead>
        <tr>
          <th>プロフィール画像</th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>写真</td>
          <td><%= attachment_image_tag @book.user, :profile_image, :fill, 100,100, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= @book.body %></td>
          <% if @bookuser.id == current_user.id %>
          <td><%= link_to "Edit", edit_book_path(@book) %></td>
          <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>

app/views/homes/show.html.erb
<div class="container">
  <div class="row">
        <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book">Bookers!</i></h1>
      </col>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to<i class="fas fa-book"></i><strong>Bookers!</strong></h1>
      <p>you can share your own opinions, expressions, and emotions</p>
      <p>about your vairous books<i class="fas fa-book"></i></p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block mb-3" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li> <%= link_to user_path(current_user.id), class: 'fas fa-home nav-link text-light' do %>Home<% end %></li>
          <li><%= link_to users_path, class: 'fas fa-users nav-link text-light' do %>Users<% end %></li>
          <li><%= link_to books_path, class: 'fas fa-book-open nav-link text-light' do %>Books<% end %></li>
          <li><%= link_to destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' do %>logout<% end %>
          <% else %>
          <li><%= link_to root_path, class: 'fas fa-home nav-link text-light' do %>Home<% end %></li>
          <li><%= link_to  homes_about_path, class: 'fas fa-link nav-link text-light' do %>User<% end %></li>
          <li><%= link_to new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' do %>Book<% end %></li>
          <li><%= link_to new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' do %>Signout<% end %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  </header>
  <main>
    <div class="container">
    <% if notice %>
　　<p><%= notice %></p>
    <% end %>
    <% if alert %>
    <p><%= alert %></p>
　　<% end %>
　　</div>
    <%= yield %>

  </main>
<footer>
  <div class="container">
    <div class="row">
      <div class="mx-auto">
    Copyright Infratop.inc
      </div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/_user_template.html.erb
<!--userの情報表示-->
<h1>User info</h1>
<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
<table class="table">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>  
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>

<!--編集画面へのリンク-->
<%= link_to edit_user_path(user.id), class: "btn btn-outline-dark btn-sm btn-block" do %>
  <i class="fas fa-user-cog"></i>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 col-md-8 col-sm-4 mx-auto">
      <%= form_with model:@user, local: true do |f| %>
        <div class="form-group">
          <%= f.label :Name %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
          <div class:form-group>
          <%= f.label :Introduction %>
          <%= f.text_field :introduction, class:"form-control" %>
        </div>
          <div class="form-group">
            <%= f.submit "更新", class:"btn btn-success" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user_template', user:@user %>
      <%= render 'books/book_template', book:@book %>
    </div>
    <div class="col-md-8">
      <h2>Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>プロフィール画像</th>
              <th>投稿者名</th>
            </tr>
          </thead>
          <tbody>
        <% @users.each do |f| %>
          <tr>
            <td><%= attachment_image_tag f, :profile_image, :fill, 100, 100, format: "jpeg", fallback: "no_image.jpg" %></td>
            <td><%= f.name %></td>
            <td><%= link_to "Show", user_path(f) %></td>
          </tr>
        <% end %>
        </tbody>
       </table>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user_template', user:@user %>
      <%= render 'books/book_template', book:@book %>
    </div>
    <div class="col-md8">
      <h2>User Book</h2>
      <table class="table">
        <thead>
          <tr>
            <th>Profile image</th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @bookuser.each do |f| %>
          <tr>
            <td><%= attachment_image_tag @user, :profile_image, :fill, 100,100, format: "jpeg", fallback: "no_image.jpg" %></td>
            <td><%= link_to f.title, book_path(f) %></td>
            <td><%= f.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>